package dev.worldbuilder.bridge;

import com.google.gson.*;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraftforge.fml.ModList;
import java.util.*;

public final class BridgeDispatcher {
    private final WorldAccess world;private final RegistryScanner registry=new RegistryScanner();private final TransactionManager transactions;private final SafetyPolicy safety=new SafetyPolicy();private final PermissionManager permissions=new PermissionManager();
    private final BuildQueue queue;private final ClipboardManager clipboards;private final GeometryEngine geometry=new GeometryEngine();private final BuildingPlanService plans;private final ExperimentManager experiments;
    public BridgeDispatcher(WorldAccess world,int historyLimit){this.world=world;transactions=new TransactionManager(world.server(),historyLimit);queue=new BuildQueue(world,transactions);clipboards=new ClipboardManager(transactions);plans=new BuildingPlanService(world,safety);experiments=new ExperimentManager(transactions);}
    public void tick(){queue.tick();}
    public Protocol.Response dispatch(Protocol.Request request){return dispatch(request,BridgePrincipal.localFallback(request==null||request.auth()==null?"unknown":request.auth().clientId()));}
    public Protocol.Response dispatch(Protocol.Request request,BridgePrincipal principal){try{if(request==null||request.operation()==null)throw new BridgeOperationException("MALFORMED_REQUEST","Request or operation is missing");if(!Protocol.VERSION.equals(request.protocolVersion()))return Protocol.Response.error(request.requestId(),"PROTOCOL_VERSION_MISMATCH","Bridge protocol is "+Protocol.VERSION);permissions.require(request,principal);JsonObject a=request.arguments()==null?new JsonObject():request.arguments();JsonElement result=switch(request.operation()){
        case "handshake"->handshake(request,principal);case "get_world_info"->world.worldInfo();case "get_dimension"->world.dimensionInfo(requiredString(a,"dimension"));case "get_players"->world.players(BridgeConfig.REFERENCE_PLAYERS.get());case "get_player_reference_position"->playerReference(a);
        case "get_block"->getBlock(a);case "scan_area"->scan(a);case "get_heightmap"->heightmap(a);case "get_biome"->biome(a);
        case "get_block_entity_info"->blockEntity(a);case "get_region_summary"->summary(a);
        case "list_mods"->registry.listMods();case "list_blocks"->registry.listBlocks(integer(a,"offset",0),bounded(integer(a,"limit",100),1,500,"limit"));case "list_items"->registry.listItems(integer(a,"offset",0),bounded(integer(a,"limit",100),1,500,"limit"));
        case "search_blocks"->registry.searchBlocks(requiredString(a,"query"),bounded(integer(a,"limit",20),1,100,"limit"));case "search_items"->registry.searchItems(requiredString(a,"query"),bounded(integer(a,"limit",20),1,100,"limit"));case "search_recipes"->world.searchRecipes(string(a,"query",""),bounded(integer(a,"limit",20),1,100,"limit"));case "get_block_info","get_block_states"->registry.blockInfo(requiredString(a,"id"));case "get_item_info"->registry.itemInfo(requiredString(a,"id"));case "get_tags"->registry.tags(requiredString(a,"registry"),stringOrNull(a,"namespace"));case "get_mod_capabilities"->capabilities();
        case "set_block"->setBlock(a,principal);case "set_blocks_batch"->batch(a,principal);case "fill_region"->fill(a,principal,null);case "replace_region"->fill(a,principal,requiredString(a,"match"));case "clear_region"->clear(a,principal);case "copy_region"->copy(a);case "paste_region"->paste(a,principal);case "rotate_region"->transform(a,principal,requiredString(a,"rotation"),"none");case "mirror_region"->transform(a,principal,"none",requiredString(a,"mirror"));
        case "build_floor","build_wall","build_box","build_column","build_beam","build_window","build_doorway","build_stairs","build_staircase","build_roof","build_gable_roof","build_hip_roof","build_flat_roof","build_circle","build_cylinder","build_tower","build_platform","build_foundation","build_path","build_road","build_fence","build_arch","build_bridge"->geometric(request.operation(),a,principal);
        case "get_build_status"->queue.status(uuid(a,"buildId"));case "cancel_build"->queue.cancel(uuid(a,"buildId"));case "undo_build"->queue.enqueueRestore(transactions.prepareUndo(uuid(a,"transactionId")),principal.auditId());case "redo_build"->queue.enqueueRestore(transactions.prepareRedo(uuid(a,"transactionId")),principal.auditId());case "get_build_history"->transactions.historyJson();
        case "validate_building_plan"->plans.validationJson(requiredObject(a,"plan"));case "estimate_build"->plans.estimateJson(requiredObject(a,"plan"));case "preview_build"->plans.preview(requiredObject(a,"plan"));case "execute_building_plan"->executePlan(a,principal);
        case "create_experiment_workspace"->createExperiment(a);case "inspect_experiment"->inspectExperiment(a);case "reset_experiment_workspace"->resetExperiment(a,principal);
        default->throw new BridgeOperationException("UNSUPPORTED_OPERATION","Unsupported operation: "+request.operation());};return Protocol.Response.ok(request.requestId(),result);
    }catch(BridgeOperationException e){return Protocol.Response.error(request==null?"unknown":request.requestId(),e.code(),e.getMessage());}catch(IllegalArgumentException|JsonParseException e){return Protocol.Response.error(request==null?"unknown":request.requestId(),"MALFORMED_REQUEST",e.getMessage());}catch(RuntimeException e){AiWorldBuilderBridge.LOGGER.error("Bridge operation failed",e);return Protocol.Response.error(request==null?"unknown":request.requestId(),"INTERNAL_ERROR",e.getMessage());}}
    private JsonObject handshake(Protocol.Request r,BridgePrincipal principal){JsonObject out=new JsonObject();out.addProperty("protocolVersion",Protocol.VERSION);out.addProperty("authenticated",true);out.addProperty("role",permissions.role(principal).name());out.addProperty("activeHost",true);out.addProperty("relay",principal.playerUuid()!=null&&!principal.integratedOwner());out.add("capabilities",capabilities());return out;}
    private JsonObject playerReference(JsonObject a){JsonObject result=world.playerReference(stringOrNull(a,"player"));String uuid=result.get("uuid").getAsString(),name=result.get("name").getAsString();if(!BridgeConfig.REFERENCE_PLAYERS.get().contains("*")&&!BridgeConfig.REFERENCE_PLAYERS.get().contains(uuid)&&!BridgeConfig.REFERENCE_PLAYERS.get().contains(name))throw new BridgeOperationException("PERMISSION_DENIED","Player position is not allowed as a reference");return result;}
    private JsonObject getBlock(JsonObject a){String d=requiredString(a,"dimension");BlockPos p=position(requiredObject(a,"position"));safety.validateRead(new Region(d,p,p),world.level(d));return world.getBlock(d,p);}
    private JsonObject biome(JsonObject a){String d=requiredString(a,"dimension");BlockPos p=position(requiredObject(a,"position"));safety.validateRead(new Region(d,p,p),world.level(d));return world.biome(d,p);}
    private JsonObject blockEntity(JsonObject a){String d=requiredString(a,"dimension");BlockPos p=position(requiredObject(a,"position"));safety.validateRead(new Region(d,p,p),world.level(d));return world.blockEntityInfo(d,p);}
    private JsonObject scan(JsonObject a){Region r=region(a);safety.validateScan(r,world.level(r.dimension()));return world.scan(r);}
    private JsonObject summary(JsonObject a){Region r=region(a);safety.validateScan(r,world.level(r.dimension()));return world.regionSummary(r);}
    private JsonObject heightmap(JsonObject a){String d=requiredString(a,"dimension");safety.validateDimension(d);int minX=requiredInt(a,"minX"),minZ=requiredInt(a,"minZ"),maxX=requiredInt(a,"maxX"),maxZ=requiredInt(a,"maxZ");int width=Math.abs(maxX-minX)+1,depth=Math.abs(maxZ-minZ)+1,max=BridgeConfig.MAX_SCAN_RADIUS.get()*2+1;if(width>max||depth>max)throw new BridgeOperationException("LIMIT_EXCEEDED","Heightmap exceeds maxScanRadius");return world.heightmap(d,minX,minZ,maxX,maxZ);}
    private JsonObject setBlock(JsonObject a,BridgePrincipal principal){String d=requiredString(a,"dimension");BlockPos p=position(requiredObject(a,"position"));Region r=new Region(d,p,p);safety.validateWrite(r,1,world.level(d));JsonObject s=requiredObject(a,"state");var tx=transactions.setBlock(world.level(d),p,WorldAccess.parseState(requiredString(s,"id"),objectOrEmpty(s,"properties")),string(a,"summary","MCP set_block"),principal.auditId(),stringOrNull(a,"referencePlayer"));return transactions.json(tx);}
    private JsonObject batch(JsonObject a,BridgePrincipal principal){String d=requiredString(a,"dimension");JsonArray array=requiredArray(a,"blocks");if(array.size()>BridgeConfig.MAX_BLOCKS_PER_BUILD.get())throw new BridgeOperationException("LIMIT_EXCEEDED","Batch exceeds maxBlocksPerBuild");List<BuildQueue.Placement> values=new ArrayList<>();for(JsonElement e:array){JsonObject b=e.getAsJsonObject(),s=requiredObject(b,"state");values.add(new BuildQueue.Placement(position(requiredObject(b,"position")),WorldAccess.parseState(requiredString(s,"id"),objectOrEmpty(s,"properties"))));}return enqueue(d,string(a,"summary","MCP batch"),principal,values,a);}
    private JsonObject fill(JsonObject a,BridgePrincipal principal,String match){Region r=region(a);BlockState state=parseState(requiredObject(a,"state"));safety.validateWrite(r,(int)Math.min(Integer.MAX_VALUE,r.volume()),world.level(r.dimension()));List<BuildQueue.Placement> values=new ArrayList<>();for(BlockPos p:r)if(match==null||net.minecraftforge.registries.ForgeRegistries.BLOCKS.getKey(world.level(r.dimension()).getBlockState(p).getBlock()).toString().equals(match))values.add(new BuildQueue.Placement(p,state));if(values.isEmpty())throw new BridgeOperationException("NOT_FOUND","No matching blocks in region");return enqueue(r.dimension(),string(a,"summary","MCP region build"),principal,values,a);}
    private JsonObject clear(JsonObject a,BridgePrincipal principal){Region r=region(a);safety.validateWrite(r,(int)Math.min(Integer.MAX_VALUE,r.volume()),world.level(r.dimension()));List<BuildQueue.Placement> values=new ArrayList<>();for(BlockPos p:r)values.add(new BuildQueue.Placement(p,Blocks.AIR.defaultBlockState()));return enqueue(r.dimension(),string(a,"summary","MCP clear"),principal,values,a);}
    private JsonObject copy(JsonObject a){Region r=region(a);safety.validateScan(r,world.level(r.dimension()));return clipboards.copy(world.level(r.dimension()),r);}
    private JsonObject paste(JsonObject a,BridgePrincipal principal){String d=requiredString(a,"dimension");List<BuildQueue.Placement> values=clipboards.paste(uuid(a,"clipboardId"),position(requiredObject(a,"target")),string(a,"rotation","none"),string(a,"mirror","none"));return enqueue(d,string(a,"summary","MCP paste"),principal,values,a);}
    private JsonObject transform(JsonObject a,BridgePrincipal principal,String rotation,String mirror){Region r=region(a);safety.validateWrite(r,(int)Math.min(Integer.MAX_VALUE,r.volume()*2),world.level(r.dimension()));return enqueue(r.dimension(),string(a,"summary","MCP transform"),principal,clipboards.transformInPlace(world.level(r.dimension()),r,rotation,mirror),a);}
    private JsonObject geometric(String operation,JsonObject a,BridgePrincipal principal){Region r=region(a);BlockState state=WorldAccess.orient(parseState(requiredObject(a,"state")),stringOrNull(a,"orientation"));List<BuildQueue.Placement> values=geometry.generate(operation,r).stream().map(p->new BuildQueue.Placement(p,state)).toList();return enqueue(r.dimension(),string(a,"summary",operation),principal,values,a);}
    private JsonObject executePlan(JsonObject a,BridgePrincipal principal){JsonObject plan=requiredObject(a,"plan");plans.requireSafePreview(plan);String d=requiredString(plan,"dimension");return enqueue(d,"BuildingPlan "+requiredString(plan,"id"),principal,plans.placements(plan),a);}
    private JsonObject createExperiment(JsonObject a){Region r=region(a);safety.validateWrite(r,(int)Math.min(Integer.MAX_VALUE,r.volume()),world.level(r.dimension()));return experiments.create(world.level(r.dimension()),r);}
    private JsonObject inspectExperiment(JsonObject a){UUID id=uuid(a,"experimentId");Region r=experiments.region(id);return experiments.inspect(id,world.level(r.dimension()));}
    private JsonObject resetExperiment(JsonObject a,BridgePrincipal principal){UUID id=uuid(a,"experimentId");Region r=experiments.region(id);return enqueue(r.dimension(),"Reset experiment "+id,principal,experiments.reset(id),a);}
    private JsonObject enqueue(String d,String summary,BridgePrincipal principal,List<BuildQueue.Placement> values,JsonObject args){Region bounds=bounds(d,values);permissions.requireBuildSize(principal,values.size());safety.validateWrite(bounds,values.size(),world.level(d));if(args.has("experimentId")){Region workspace=experiments.region(UUID.fromString(args.get("experimentId").getAsString()));if(!workspace.dimension().equals(d)||values.stream().anyMatch(p->!workspace.contains(p.position())))throw new BridgeOperationException("PERMISSION_DENIED","Build escapes experiment workspace");}return queue.enqueue(d,summary,principal.auditId(),stringOrNull(args,"referencePlayer"),values);}
    private JsonObject capabilities(){CreateIntegration.Status create=new CreateIntegration().detect();JsonObject out=new JsonObject();JsonArray generic=new JsonArray();List.of("registry_blocks","registry_items","blockstate","transactions","batch_build","building_plan","experiments").forEach(generic::add);out.add("generic",generic);JsonObject c=new JsonObject();c.addProperty("installed",create.installed());c.addProperty("version",create.version());c.addProperty("advancedAdapterAvailable",create.advancedAdapterAvailable());out.add("create",c);return out;}
    private static Region bounds(String d,List<BuildQueue.Placement> v){if(v.isEmpty())throw new BridgeOperationException("MALFORMED_REQUEST","No placements");int minX=Integer.MAX_VALUE,minY=Integer.MAX_VALUE,minZ=Integer.MAX_VALUE,maxX=Integer.MIN_VALUE,maxY=Integer.MIN_VALUE,maxZ=Integer.MIN_VALUE;for(var p:v){BlockPos b=p.position();minX=Math.min(minX,b.getX());minY=Math.min(minY,b.getY());minZ=Math.min(minZ,b.getZ());maxX=Math.max(maxX,b.getX());maxY=Math.max(maxY,b.getY());maxZ=Math.max(maxZ,b.getZ());}return new Region(d,new BlockPos(minX,minY,minZ),new BlockPos(maxX,maxY,maxZ));}
    private static Region region(JsonObject a){return new Region(requiredString(a,"dimension"),position(requiredObject(a,"min")),position(requiredObject(a,"max")));}
    private static BlockState parseState(JsonObject s){return WorldAccess.parseState(requiredString(s,"id"),objectOrEmpty(s,"properties"));}
    private static BlockPos position(JsonObject j){return new BlockPos(requiredInt(j,"x"),requiredInt(j,"y"),requiredInt(j,"z"));}
    private static JsonObject requiredObject(JsonObject j,String n){if(!j.has(n)||!j.get(n).isJsonObject())throw new BridgeOperationException("MALFORMED_REQUEST","Missing object: "+n);return j.getAsJsonObject(n);}private static JsonObject objectOrEmpty(JsonObject j,String n){return j.has(n)&&j.get(n).isJsonObject()?j.getAsJsonObject(n):new JsonObject();}
    private static JsonArray requiredArray(JsonObject j,String n){if(!j.has(n)||!j.get(n).isJsonArray())throw new BridgeOperationException("MALFORMED_REQUEST","Missing array: "+n);return j.getAsJsonArray(n);}private static String requiredString(JsonObject j,String n){if(!j.has(n)||!j.get(n).isJsonPrimitive())throw new BridgeOperationException("MALFORMED_REQUEST","Missing string: "+n);return j.get(n).getAsString();}private static int requiredInt(JsonObject j,String n){if(!j.has(n))throw new BridgeOperationException("MALFORMED_REQUEST","Missing integer: "+n);return j.get(n).getAsInt();}private static int integer(JsonObject j,String n,int f){return j.has(n)?j.get(n).getAsInt():f;}private static String string(JsonObject j,String n,String f){return j.has(n)?j.get(n).getAsString():f;}private static String stringOrNull(JsonObject j,String n){return j.has(n)?j.get(n).getAsString():null;}private static UUID uuid(JsonObject j,String n){return UUID.fromString(requiredString(j,n));}private static int bounded(int n,int min,int max,String field){if(n<min||n>max)throw new BridgeOperationException("LIMIT_EXCEEDED",field+" must be between "+min+" and "+max);return n;}
}
